### PR TITLE
Back out the robot's vote from the tally

### PR DESCRIPTION
**Pull request by blurfl**
Also update the robot's comment to urge the author to vote.

### CODE REVIEW

**Comment by BarbourSmith** [comment]
This looks perfect. Can't wait to vote for it. ❤️  👍 👍

**Comment by BarbourSmith** [comment]
I'm not sure why the robot keeps commenting but I will look into it!

**Comment by blurfl** [comment]
Our two 
PRs touched the same line, mine failed because of that. My attempt to correct it seems not to be the right approach.

**Comment by blurfl** [comment]
Github is having problems - that might be part of it?
https://www.theregister.co.uk/2018/10/22/github_down_storage_failure/

**Pull request merged**
